### ISSUE TITLE
Search Engine Optimization

### ISSUE THREAD

**Issue by paulhayes** [sdesalas/node-pi-zero#15]
After trying to find this project on google and for a while without success, I've realised this has a lot to do with raspberry not being in the repository name. I luckily only found it again due to the star I gave it. But I worry others aren't finding this really useful project. Would you consider renaming it to node-raspberry-pi-zero-installation.

edit: realised the description does include Raspberry.

**Comment by rgstephens** [comment]
I'll second the value of this project.  Nice work!

**Comment by sdesalas** [comment]
Thanks @rgstephens ! 

Not convinced the longer name adds much value @paulhayes .. I've got it listed as no 2 result on google.

Thanks for suggestion but i'll give it a miss.. ill keep ticket open for a bit in case there is an overwhelming support for it.

![screenshot_20180110-230019](https://user-images.githubusercontent.com/534414/34771869-f860ffd8-f5fd-11e7-9bdb-f160f03458e9.png)

**Comment by paulhayes** [comment]
Okay, I know that looks promising. But search for just "raspberry pi node js" and it's won't be in the results at all ( I just checked, I got as far as page 5 before I gave up ). 

As these instructions aren't explicitly for the zero ( they work fine for the other pi's I have ). I thought you might be missing out on the whole educational pi users crowd. Who need help like this the most.
