### ISSUE TITLE
Node v12?

### ISSUE THREAD

**Issue by rafamel** [sdesalas/node-pi-zero#20]
Any plans on adding a script for Node 12?

**Comment by sdesalas** [comment]
Happy to merge a PR if you are offering.

**Comment by deftdawg** [comment]
Hey @rafamel a quick FYI, armv6l (which is what the Pi Zero's CPU see /proc/cpuinfo) builds of node are no longer officially supported, however they are available as experimental (meaning they no longer have unit tests validated) builds from here:

https://unofficial-builds.nodejs.org/download/release

For my application, I've been able to just download 12.14.1 like this:
```shell
export NODE_VER=12.14.1
if ! node --version | grep -q ${NODE_VER}; then
  (cat /proc/cpuinfo | grep -q "Pi Zero") && if [ ! -d node-v${NODE_VER}-linux-armv6l ]; then
    echo "Installing nodejs ${NODE_VER} for armv6 from unofficial builds..."
    curl -O https://unofficial-builds.nodejs.org/download/release/v${NODE_VER}/node-v${NODE_VER}-linux-armv6l.tar.xz 
    tar -xf node-v${NODE_VER}-linux-armv6l.tar.xz 
  fi
  echo "Adding node to the PATH"
  PATH=$(pwd)/node-v${NODE_VER}-linux-armv6l/bin:${PATH}
fi
node --version # or whatever ....
```

**Comment by sdesalas** [comment]
Updated, you should now be able to use the same CLI scripts for v12+.

Its basically downloading the tarballs from the [Unofficial Builds Project](https://github.com/nodejs/unofficial-builds/).

See explanation here:

https://github.com/sdesalas/node-pi-zero#node-in-v12-experimental
